name: Build Workflow

on:
  push:
    # Pattern matched against refs/tags
    tags:        
        - "v*.*.*"

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
        contents: write
        pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.11.7'
      - name: Install Requirements
        run: |
          pip install -r requirements.txt
      - name: Run PyInstaller
        run: |
          python -m PyInstaller DutchLingo.spec
      - uses: actions/upload-artifact@v2
        with:
          name: DutchLingoApplication
          path: dist/DutchLingo/DutchLingo.exe
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          artifacts: dist/DutchLingo/DutchLingo.exe